version: '3.9'

services:
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres

        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_PW: postgres
            POSTGRES_DB: postgres
            PGDATA: /data/postgres
        volumes:
            - ~/dockerfiles/postgres:/var/lib/postgresql/data
            # - /home/runneruser/1234:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    postgres:
