name: Create Environment File

on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string

jobs:
    create-env:
        runs-on: ubuntu-latest
        steps:
            - name: Create .env file
              run: |
                  echo "Creating .env file for ${{ inputs.environment }} environment"
                  cat << EOF > .env.${{ inputs.environment }}
                  ENVIRONMENT=${{ inputs.environment }}
                  ENABLE_GOOGLE_AUTH=${{ secrets.ENABLE_GOOGLE_AUTH }}
                  GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
                  GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}

                  ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}
                  ENCRYPTION_IV=${{ secrets.ENCRYPTION_IV }}

                  NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
                  NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
                  NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}"
                  POSTGRES_DB=${{ secrets.POSTGRES_DB }}
                  POSTGRES_DB=${{ secrets.DB_NAME }}
                  POSTGRES_USER=${{ secrets.DB_USER }}
                  POSTGRES_PW=${{ secrets.DB_PASSWORD }}
                  DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.POSTGRES_PW }}@localhost:5432/${{ secrets.POSTGRES_DB }}
                  EOF
              continue-on-error: true

            - name: Upload env file
              uses: actions/upload-artifact@v3
              with:
                  name: env-file
                  path: .env.${{ inputs.environment }}
                  retention-days: 1
              continue-on-error: true
