name: Node.js CI/CD

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Name of the PM2 app to start"
        required: true
        default: "pdf_konsek"
        type: string
      action:
        description: "Action to perform (start, restart, stop)"
        required: true
        default: "restart"
        type: choice
        options:
          - start
          - restart
          - stop

  push:
    branches: ["production"]

jobs:
  manage-pm2:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run startup script and manage PM2 ecosystem
        run: |
          pm2 ${{ github.event.inputs.action }} ${{ github.event.inputs.app_name }}

      - name: Verify PM2 process
        run: |
          if pm2 describe ${{ github.event.inputs.app_name }} > /dev/null 2>&1; then
            echo "Die Anwendung ${{ github.event.inputs.app_name }} läuft erfolgreich."
          else
            echo "Fehler: Die Anwendung ${{ github.event.inputs.app_name }} konnte nicht gestartet werden."
            exit 1
