name: Node.js

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Name of the PM2 app to start"
        required: true
        default: "pdf_konsek"
        type: string
      action:
        description: "Action to perform (start, restart, stop)"
        required: true
        default: "restart"
        type: choice
        options:
          - start
          - restart
          - stop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Verify environment setup
        run: |
          if [ -s ".env" ]; then
            echo ".env file exists and is not empty."
          else
            echo ".env file is missing or empty."
            exit 1
          fi

      - name: Check PM2 installation
        run: |
          . ~/.nvm/nvm.sh
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 is not installed."
            npm install -g pm2
          else
            echo "PM2 is installed."
          fi
          pm2 --version

      - name: Run startup script and manage PM2 ecosystem
        run: |
          . ~/.nvm/nvm.sh
          pm2 ${{ github.event.inputs.action }} ${{ github.event.inputs.app_name }}
