name: Node.js

on:
    push:
        branches: ['production']

jobs:
    build:
        runs-on: self-hosted
        defaults:
            run:
                working-directory: ${{ github.workspace }}

        env:
            NODE_ENV: production
            ENABLE_GOOGLE_AUTH: ${{ secrets.ENABLE_GOOGLE_AUTH }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
            ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
            NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DATABASE_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check Node.js version
              run: |
                  . ~/.nvm/nvm.sh
                  echo "Node.js version: $(node -v)"
                  echo "npm version: $(npm -v)"

            - name: Cache für schnelles Deployment node-modules
              uses: actions/cache@v4
              id: cache-nodemodules
              with:
                  path: |
                      **/node_modules
                      ~/.npm
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-

              continue-on-error: true
            - name: Cache für  Next.js build
              uses: actions/cache@v4
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.{js,jsx,ts,tsx,cjs,mjs}')}}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
                      ${{ runner.os }}-nextjs-
              continue-on-error: true

            - name: Install dependencies
              run: |
                  . ~/.nvm/nvm.sh
                  export NVM_DIR="$HOME/.nvm"

            - name: Build
              run: npm run build

            - name: Run Deployment
              run: |
                  . ~/.nvm/nvm.sh
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  pm2 --version
                  NODE_PATH=$(which node)
                  PM2_EXEC_PATH=$(which pm2)
                  echo "Node path: $NODE_PATH"
                  echo "PM2 path: $PM2_EXEC_PATH"
                  $PM2_EXEC_PATH
                  pm2 restart ecosystem.config.cjs
              continue-on-error: true
